# Generated by Django 4.0.5 on 2022-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                #('category', models.CharField(choices=[('clothes', 'Clothes'), ('food', 'Food'), ('for_home', 'For home')], default='none', max_length=50)))
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
