# Generated by Django 4.0.5 on 2022-07-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
